alias edclean="rm -f *~"
alias f="finger"
alias dir="ls -alg"
alias dirn="lsn -alg"
alias ls="ls --color=auto -F"
alias lsn="/bin/ls"
alias copy="cp"
alias gz="gzip -best"
alias guz="gunzip"
alias sb="source ~/.bashrc"
alias vi="vim"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"

alias screen="TERM=screen screen"
